In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.8.0


### Basic OPerations

In [3]:
# Step 1: Build the Graph
a = tf.constant(1)
b = tf.constant(2)
c = tf.add(a,b)

In [4]:
print(c)

Tensor("Add:0", shape=(), dtype=int32)


In [5]:
# Step 2: Execute the Graph
sess = tf.Session()
print(sess.run(a))
print(sess.run(b))
print(sess.run(c))

1
2
3


In [6]:
# Data Type
# Normally that is how you type Python
a = 4
b = 5.6
print(a*b)

22.4


In [7]:
a = tf.constant(4,dtype=tf.float32)
b = tf.constant(5.6,dtype=tf.float32)
c = tf.multiply(a,b)

In [8]:
print(c)

Tensor("Mul:0", shape=(), dtype=float32)


In [9]:
print(sess.run(c))

22.4


In [10]:
a = tf.constant(1.8,dtype=tf.float32)
b = tf.cast(a, tf.int32)

In [14]:
print(sess.run(a))
print(sess.run(b))

1.8
1


In [15]:
# TF Math Operations
a = tf.constant(2)
b = tf.constant(3)

In [27]:
c = tf.exp(2.)
print(sess.run(c))

7.38906


In [28]:
# Exercise d = (a*b) + c
a = tf.constant(3,dtype=tf.float32)
b = tf.constant(4.1,dtype=tf.float32)
c = tf.constant(5,dtype=tf.float32)
d = tf.add(tf.multiply(a,b),c)

print(sess.run(d))

17.3


In [30]:
# Matrix
a = tf.constant([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(sess.run(a))
print(sess.run(tf.shape(a)))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 3]


In [31]:
# Tensor Shape and Slice
b = tf.slice(a,[1,1],[2,2])
print(sess.run(b))

[[5 6]
 [8 9]]


In [34]:
# Basic Matrix Operations
a = tf.constant([[1,2],[3,4]])
b = tf.constant([[4,3],[2,1]])
# c = tf.add(a,b)
# c = tf.transpose(a)
c = tf.matmul(a,b)
print(sess.run(c))

[[ 8  5]
 [20 13]]


In [35]:
# Exercise
x = tf.constant([[1.1,1.2]],dtype=tf.float32)
w = tf.constant([[1,2],[3,4]],dtype=tf.float32)
b = tf.constant([[2.3,2.5]],dtype=tf.float32)
y = tf.matmul(x,w)+b
print(sess.run(y))

[[ 7.   9.5]]


In [39]:
# Random Numbers
tf.set_random_seed(2)
a = tf.random_normal([2,3],mean=0,stddev=0.1)
# b = tf.truncated_normal([2,3],mean=0,stddev=0.1)
print(sess.run(a))
# print(sess.run(b))

[[-0.02820737  0.09275482  0.1442049 ]
 [ 0.03593154 -0.02148513  0.04611695]]
[[ 0.18110301  0.06311748  0.12516394]
 [ 0.19408594  0.14380388 -0.06879967]]


In [40]:
# Comparison
a = tf.constant(2)
b = tf.constant(3)
print(sess.run(tf.minimum(a,b)))
print(sess.run(tf.maximum(a,b)))

2
3


In [44]:
# Exercise: Argmin and Argmax
a = tf.constant([13,2,20,10,1,2,3])
print(sess.run(tf.argmin(a)))
print(sess.run(tf.argmax(a)))

4
2


In [48]:
# Ex: Reduced Sum
a = tf.constant(
                [[1,1,1],
                [2,2,2]]
                )
#print(sess.run(tf.reduce_sum(a)))
print(sess.run(tf.reduce_sum(a, 0))) # Column sum
print(sess.run(tf.reduce_sum(a, 1)))

[3 3 3]
[3 6]


In [53]:
# Special Matrices
a = tf.zeros([2,3])
b = tf.ones([2,3])
c = tf.diag(tf.ones(2))
d = tf.fill([2,3],2)
e = tf.eye(3)
print(sess.run(a))
print(sess.run(b))
print(sess.run(c))
print(sess.run(d))
print(sess.run(e))

[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 1.  0.]
 [ 0.  1.]]
[[2 2 2]
 [2 2 2]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [52]:
a = tf.linspace(-1., 1., 10)
print(sess.run(a))

[-1.         -0.77777779 -0.55555558 -0.33333331 -0.1111111   0.11111116
  0.33333337  0.55555558  0.77777779  1.        ]


In [55]:
# Placeholder
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)
sum = tf.add(a,b)
print(sess.run(sum,{a:3,b:4}))
print(sess.run(sum,feed_dict={a:3,b:4}))

7.0
7.0


In [61]:
# Challenge

x = tf.placeholder(tf.float32,shape=[1,2])
w = tf.placeholder(tf.float32,shape=[2,2])
b = tf.constant([[2.3,2.5]],tf.float32)
y = tf.add(tf.matmul(x,w),b)
print(sess.run(y,feed_dict={
     x:[[1.1,1.2]],
     w:[[1,2],[3,4]]})
       )

[[ 7.   9.5]]


In [62]:
# Variables
W = tf.Variable([1.], tf.float32)
b = tf.Variable([-1.], tf.float32)
x = tf.placeholder(tf.float32)
y = W * x + b

In [63]:
init = tf.global_variables_initializer()
sess.run(init)
print(sess.run(y, {x:[1,2,3,4]}))

[ 0.  1.  2.  3.]
